Mobile version skeleton for first two sections
StarMindz/Portfolio-setup-and-mobile-version-skeleton pull request #1
Opened 2022-07-01 00:49 UTC by StarMindz

I created the first two sections of the mobile version for the portfolio project. The first two sections are the toolbar/header and the headline section

2022-07-01 02:41 UTC, topeogunleye reviewed
Hi @StarMindz, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ⚠️

   - You have submitted a project that has failing linters, Kindly make sure your linters are all passing before submitting the PR.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

>Invalid Code Review Request **does not count** into the code reviews limit.

2022-07-01 11:50 UTC, muneebulrehman requested changes
Hi @StarMindz , 

Good job so far! I see you put a lot of effort into this project. However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- No linter errors

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 - Consider sticking to the Figma template of your choosing. Use the same margin, padding and font settings as in the Figma template.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-01 11:50 UTC, muneebulrehman commented on index.html
> +</html>
There is some white space all along the right side of your application. Kindly fix it. 
![image](https://user-images.githubusercontent.com/33268927/176888147-bb228dbd-b5a5-45c5-8375-9e404500d8f3.png)

2022-07-01 11:50 UTC, muneebulrehman commented on index.html
> +    </section>
Let's wrap this section in a header tag, that would make more sense, don't you think so?

2022-07-01 11:50 UTC, muneebulrehman commented on index.html
> +        <h1 id="name">John Doe</h1>
Let's make the logo a clickable link, so when a visitor clicks on it, he/she is redirected back to home page.

2022-07-01 11:50 UTC, muneebulrehman commented on index.html
> +        <div id="menu"><a href=""><img src="images/menu.png" alt=""></a></div>
Let's wrap the hamburger icon in a `nav` tag.

2022-07-01 11:50 UTC, muneebulrehman commented on index.html
> +            I’m Alex</h3>
Consider making this heading as h1, since the introduction should be the first thing visible.

2022-07-01 11:50 UTC, muneebulrehman commented on index.html
> +            don’t hestiate to contact me.</div>
Instead of using div, we can use a `p` tag for this text, since this is a paragraph and that would make more sense.

2022-07-01 11:50 UTC, muneebulrehman commented on index.html
> +        </div>
Let's make this div a `ul` and each image a child of the list.

2022-07-01 19:41 UTC, 1GORDON requested changes
##
## Hi @StarMindz ✋

Good job so far!

## Highlights!
- Good feature branch name ✔️ 
- Good commit messages  ✔️ 
- Professional Pull Request ✔️
- Linters are passing ✔️

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️

- [ ] It is important that you have a Readme file in your project and please customize it accordingly. You may use this [Readme template](https://github.com/microverseinc/readme-template/blob/master/README.md) for more clarity.

_Check the comments under the review._.

## Optional suggestions

- [ ] [Optional] Always include node_modules in your .gitignore file
- [ ] [Optional] It is also advisable to have all linter files in your project.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-01 19:41 UTC, 1GORDON commented on style.css
> +}
Great job so far @StarMindz 🤝

- [ ] Just like the previous reviewer pointed out. Try to fix the white space on the right side of your design. You may try to remove the padding-left. It seems it's the value-creating this white space.
- Your design
![padding](https://user-images.githubusercontent.com/63917725/176956795-85677c89-1ada-4fcb-8d70-20f5ca8d316e.PNG)

2022-07-01 19:41 UTC, 1GORDON commented on style.css
> +  height: 27px;
Great work @StarMindz 🤝

- [ ] [Optional] It is advisable to always use class selectors instead of IDs to select multiple properties.

2022-07-02 10:21 UTC, cynthiainga requested changes
Hi @StarMindz , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Highlights

- [ ] All linters are passing :heavy_check_mark: 

 ## Required Changes ♻️

- [ ] Please kindly check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-02 10:21 UTC, cynthiainga commented on style.css
> +}
- [ ] As mentioned by the previous reviewer kindly fix the white space on the right side of your page, you still have the white space.
![Screenshot from 2022-07-02 11-29-53](https://user-images.githubusercontent.com/74501523/176995246-cf695d15-3771-4a65-be3f-1a57215e4ea8.png)

- [ ] To fix it you need to your background image to your `.body` class not create a `div` just for your background image, and then you can arrange your image :upside_down_face: :upside_down_face:

2022-07-02 22:13 UTC, tufoinnkuo10 approved these changes
## Status: Approved :heavy_check_mark:

Hi @StarMindz 

Your project is complete! Great job for making all the requested changes🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- Validations correctly implemented
- No linter errors

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-03 05:42 UTC, merged